### ISSUE TITLE
Inside axum handler - decision evaluate method causing compile error - missing Send?

### ISSUE THREAD

**Issue by andymk-dev** [gorules/zen#127]
Inside axum handler:

    let root = env::var("RULES_ROOT").expect("RULES_ROOT missing");

    let engine = DecisionEngine::new(FilesystemLoader::new(FilesystemLoaderOptions {
        keep_in_memory: true, // optionally, keep in memory for increase performance
        root,
    }));

    let decision = engine.get_decision("test.json").await.unwrap();
    // the line below causes axum not able to recognize as handler or compiler to fail. cx is a serde_json::Value instance
    let result = decision.evaluate(&cx).await.unwrap();

This seems related to https://github.com/tokio-rs/axum/discussions/1675

axum::debug_handler shows the following long message:

std::rc::Rc<rquickjs_core::safe_ref::Mut<rquickjs_core::runtime::raw::RawRuntime>>` cannot be sent between threads safely
within `impl std::future::Future<Output = impl axum::response::IntoResponse>`, the trait `std::marker::Send` is not implemented for `std::rc::Rc<rquickjs_core::safe_ref::Mut<rquickjs_core::runtime::raw::RawRuntime>>`, which is required by `impl std::future::Future<Output = impl axum::response::IntoResponse>: std::marker::Send`
required because it captures the following types: `zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, zen_engine::NodeError>>`
required because it captures the following types: `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`
required because it captures the following types: `axum::extract::State<routes::AppState>`, `std::sync::Arc<zen_engine::DecisionEngine<zen_engine::loader::FilesystemLoader>>`, `axum::Json<routes::uw::PolicyInput>`, `routes::uw::PolicyInput`, `serde_json::Value`, `zen_engine::Decision<zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::Decision<zen_engine::loader::FilesystemLoader>, std::boxed::Box<zen_engine::loader::LoaderError>>>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view://diagnostic%20message%20%5B4%5D?4#file%3A%2F%2F%2FUsers%2Fakim%2Fio%2Frs%2Fxp-zen-engine%2Fsrc%2Froutes%2Fuw.rs)
uw.rs(12, 1): within this `impl std::future::Future<Output = impl axum::response::IntoResponse>`
base.rs(32, 12): required because it appears within the type `rquickjs_core::runtime::base::Runtime`
option.rs(571, 10): required because it appears within the type `std::option::Option<rquickjs_core::runtime::base::Runtime>`
graph.rs(24, 12): required because it appears within the type `zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`
decision.rs(64, 62): required because it's used within this `async` fn body
decision.rs(55, 62): required because it's used within this `async` fn body
uw.rs(15, 24): required because it's used within this `async` fn body
uw.rs(11, 1): required by a bound in `routes::uw::__axum_macros_check_evaluate_referral_future::check`
`dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>` cannot be sent between threads safely
the trait `std::marker::Send` is not implemented for `dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, which is required by `impl std::future::Future<Output = impl axum::response::IntoResponse>: std::marker::Send`
required for `std::ptr::Unique<dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>>` to implement `std::marker::Send`
required because it captures the following types: `&mut zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `&serde_json::Value`, `std::time::Instant`, `zen_engine::handler::traversal::GraphWalker`, `std::option::Option<std::collections::HashMap<std::string::String, zen_engine::DecisionGraphTrace>>`, `std::option::Option<(petgraph::graph_impl::NodeIndex, serde_json::Value)>`, `petgraph::graph_impl::NodeIndex`, `serde_json::Value`, `&zen_engine::model::DecisionNode`, `std::time::Instant`, `zen_engine::handler::node::NodeRequest<'_>`, `zen_engine::handler::function::FunctionHandler`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::decision::DecisionHandler<zen_engine::loader::FilesystemLoader>`, `std::pin::Pin<std::boxed::Box<dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>>>`, `zen_engine::handler::table::zen::DecisionTableHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::expression::ExpressionHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`
required because it captures the following types: `zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, zen_engine::NodeError>>`
required because it captures the following types: `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`
required because it captures the following types: `axum::extract::State<routes::AppState>`, `std::sync::Arc<zen_engine::DecisionEngine<zen_engine::loader::FilesystemLoader>>`, `axum::Json<routes::uw::PolicyInput>`, `routes::uw::PolicyInput`, `serde_json::Value`, `zen_engine::Decision<zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::Decision<zen_engine::loader::FilesystemLoader>, std::boxed::Box<zen_engine::loader::LoaderError>>>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view://diagnostic%20message%20%5B8%5D?8#file%3A%2F%2F%2FUsers%2Fakim%2Fio%2Frs%2Fxp-zen-engine%2Fsrc%2Froutes%2Fuw.rs)
boxed.rs(196, 12): required because it appears within the type `std::boxed::Box<dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>>`
pin.rs(1090, 12): required because it appears within the type `Pin<Box<dyn Future<Output = Result<NodeResponse, Error>>>>`
graph.rs(123, 99): required because it's used within this `async` fn body
decision.rs(64, 62): required because it's used within this `async` fn body
decision.rs(55, 62): required because it's used within this `async` fn body
uw.rs(15, 24): required because it's used within this `async` fn body
uw.rs(11, 1): required by a bound in `routes::uw::__axum_macros_check_evaluate_referral_future::check`
`std::rc::Rc<rquickjs_core::safe_ref::Mut<rquickjs_core::runtime::raw::RawRuntime>>` cannot be shared between threads safely
within `zen_engine::handler::function::FunctionHandler`, the trait `std::marker::Sync` is not implemented for `std::rc::Rc<rquickjs_core::safe_ref::Mut<rquickjs_core::runtime::raw::RawRuntime>>`, which is required by `impl std::future::Future<Output = impl axum::response::IntoResponse>: std::marker::Send`
required for `&zen_engine::handler::function::FunctionHandler` to implement `std::marker::Send`
required because it captures the following types: `&mut zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `&serde_json::Value`, `std::time::Instant`, `zen_engine::handler::traversal::GraphWalker`, `std::option::Option<std::collections::HashMap<std::string::String, zen_engine::DecisionGraphTrace>>`, `std::option::Option<(petgraph::graph_impl::NodeIndex, serde_json::Value)>`, `petgraph::graph_impl::NodeIndex`, `serde_json::Value`, `&zen_engine::model::DecisionNode`, `std::time::Instant`, `zen_engine::handler::node::NodeRequest<'_>`, `zen_engine::handler::function::FunctionHandler`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::decision::DecisionHandler<zen_engine::loader::FilesystemLoader>`, `std::pin::Pin<std::boxed::Box<dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>>>`, `zen_engine::handler::table::zen::DecisionTableHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::expression::ExpressionHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`
required because it captures the following types: `zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, zen_engine::NodeError>>`
required because it captures the following types: `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`
required because it captures the following types: `axum::extract::State<routes::AppState>`, `std::sync::Arc<zen_engine::DecisionEngine<zen_engine::loader::FilesystemLoader>>`, `axum::Json<routes::uw::PolicyInput>`, `routes::uw::PolicyInput`, `serde_json::Value`, `zen_engine::Decision<zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::Decision<zen_engine::loader::FilesystemLoader>, std::boxed::Box<zen_engine::loader::LoaderError>>>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view://diagnostic%20message%20%5B9%5D?9#file%3A%2F%2F%2FUsers%2Fakim%2Fio%2Frs%2Fxp-zen-engine%2Fsrc%2Froutes%2Fuw.rs)
base.rs(32, 12): required because it appears within the type `rquickjs_core::runtime::base::Runtime`
mod.rs(15, 12): required because it appears within the type `zen_engine::handler::function::FunctionHandler`
mod.rs(27, 73): required because it's used within this `async` fn body
graph.rs(123, 99): required because it's used within this `async` fn body
decision.rs(64, 62): required because it's used within this `async` fn body
decision.rs(55, 62): required because it's used within this `async` fn body
uw.rs(15, 24): required because it's used within this `async` fn body
uw.rs(11, 1): required by a bound in `routes::uw::__axum_macros_check_evaluate_referral_future::check`
`std::cell::Cell<std::ptr::NonNull<bumpalo::ChunkFooter>>` cannot be shared between threads safely
within `bumpalo::Bump`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<std::ptr::NonNull<bumpalo::ChunkFooter>>`, which is required by `impl std::future::Future<Output = impl axum::response::IntoResponse>: std::marker::Send`
if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock`
required for `&bumpalo::Bump` to implement `std::marker::Send`
required for `hashbrown::raw::RawTable<(&str, &zen_expression::vm::variable::Variable<'_>), hashbrown::BumpWrapper<'_>>` to implement `std::marker::Send`
required because it appears within the type `&mut zen_expression::vm::variable::Variable<'_>`
required because it captures the following types: `&mut zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `&serde_json::Value`, `std::time::Instant`, `zen_engine::handler::traversal::GraphWalker`, `std::option::Option<std::collections::HashMap<std::string::String, zen_engine::DecisionGraphTrace>>`, `std::option::Option<(petgraph::graph_impl::NodeIndex, serde_json::Value)>`, `petgraph::graph_impl::NodeIndex`, `serde_json::Value`, `&zen_engine::model::DecisionNode`, `std::time::Instant`, `zen_engine::handler::node::NodeRequest<'_>`, `zen_engine::handler::function::FunctionHandler`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::decision::DecisionHandler<zen_engine::loader::FilesystemLoader>`, `std::pin::Pin<std::boxed::Box<dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>>>`, `zen_engine::handler::table::zen::DecisionTableHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::expression::ExpressionHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`
required because it captures the following types: `zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, zen_engine::NodeError>>`
required because it captures the following types: `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`
required because it captures the following types: `axum::extract::State<routes::AppState>`, `std::sync::Arc<zen_engine::DecisionEngine<zen_engine::loader::FilesystemLoader>>`, `axum::Json<routes::uw::PolicyInput>`, `routes::uw::PolicyInput`, `serde_json::Value`, `zen_engine::Decision<zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::Decision<zen_engine::loader::FilesystemLoader>, std::boxed::Box<zen_engine::loader::LoaderError>>>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view://diagnostic%20message%20%5B10%5D?10#file%3A%2F%2F%2FUsers%2Fakim%2Fio%2Frs%2Fxp-zen-engine%2Fsrc%2Froutes%2Fuw.rs)
lib.rs(292, 12): required because it appears within the type `bumpalo::Bump`
lib.rs(174, 12): required because it appears within the type `hashbrown::BumpWrapper<'_>`
map.rs(188, 12): required because it appears within the type `HashMap<&str, &Variable<'_>, BuildHasherDefault<AHasher>, BumpWrapper<'_>>`
variable.rs(17, 10): required because it appears within the type `zen_expression::vm::variable::Variable<'_>`
option.rs(571, 10): required because it appears within the type `std::option::Option<&mut zen_expression::vm::variable::Variable<'_>>`
isolate.rs(24, 12): required because it appears within the type `zen_expression::isolate::Isolate<'_>`
zen.rs(22, 12): required because it appears within the type `zen_engine::handler::table::zen::DecisionTableHandler<'_>`
graph.rs(123, 99): required because it's used within this `async` fn body
decision.rs(64, 62): required because it's used within this `async` fn body
decision.rs(55, 62): required because it's used within this `async` fn body
uw.rs(15, 24): required because it's used within this `async` fn body
uw.rs(11, 1): required by a bound in `routes::uw::__axum_macros_check_evaluate_referral_future::check`
`std::cell::Cell<std::option::Option<usize>>` cannot be shared between threads safely
within `bumpalo::Bump`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<std::option::Option<usize>>`, which is required by `impl std::future::Future<Output = impl axum::response::IntoResponse>: std::marker::Send`
if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock`
required for `&bumpalo::Bump` to implement `std::marker::Send`
required for `hashbrown::raw::RawTable<(&str, &zen_expression::vm::variable::Variable<'_>), hashbrown::BumpWrapper<'_>>` to implement `std::marker::Send`
required because it appears within the type `&mut zen_expression::vm::variable::Variable<'_>`
required because it captures the following types: `&mut zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `&serde_json::Value`, `std::time::Instant`, `zen_engine::handler::traversal::GraphWalker`, `std::option::Option<std::collections::HashMap<std::string::String, zen_engine::DecisionGraphTrace>>`, `std::option::Option<(petgraph::graph_impl::NodeIndex, serde_json::Value)>`, `petgraph::graph_impl::NodeIndex`, `serde_json::Value`, `&zen_engine::model::DecisionNode`, `std::time::Instant`, `zen_engine::handler::node::NodeRequest<'_>`, `zen_engine::handler::function::FunctionHandler`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::decision::DecisionHandler<zen_engine::loader::FilesystemLoader>`, `std::pin::Pin<std::boxed::Box<dyn std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>>>`, `zen_engine::handler::table::zen::DecisionTableHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`, `zen_engine::handler::expression::ExpressionHandler<'_>`, `impl std::future::Future<Output = std::result::Result<zen_engine::handler::node::NodeResponse, anyhow::Error>>`
required because it captures the following types: `zen_engine::handler::graph::DecisionGraph<'_, zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, zen_engine::NodeError>>`
required because it captures the following types: `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`
required because it captures the following types: `axum::extract::State<routes::AppState>`, `std::sync::Arc<zen_engine::DecisionEngine<zen_engine::loader::FilesystemLoader>>`, `axum::Json<routes::uw::PolicyInput>`, `routes::uw::PolicyInput`, `serde_json::Value`, `zen_engine::Decision<zen_engine::loader::FilesystemLoader>`, `impl std::future::Future<Output = std::result::Result<zen_engine::Decision<zen_engine::loader::FilesystemLoader>, std::boxed::Box<zen_engine::loader::LoaderError>>>`, `impl std::future::Future<Output = std::result::Result<zen_engine::DecisionGraphResponse, std::boxed::Box<zen_engine::EvaluationError>>>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view://diagnostic%20message%20%5B11%5D?11#file%3A%2F%2F%2FUsers%2Fakim%2Fio%2Frs%2Fxp-zen-engine%2Fsrc%2Froutes%2Fuw.rs)
lib.rs(292, 12): required because it appears within the type `bumpalo::Bump`
lib.rs(174, 12): required because it appears within the type `hashbrown::BumpWrapper<'_>`
map.rs(188, 12): required because it appears within the type `HashMap<&str, &Variable<'_>, BuildHasherDefault<AHasher>, BumpWrapper<'_>>`
variable.rs(17, 10): required because it appears within the type `zen_expression::vm::variable::Variable<'_>`
option.rs(571, 10): required because it appears within the type `std::option::Option<&mut zen_expression::vm::variable::Variable<'_>>`
isolate.rs(24, 12): required because it appears within the type `zen_expression::isolate::Isolate<'_>`
zen.rs(22, 12): required because it appears within the type `zen_engine::handler::table::zen::DecisionTableHandler<'_>`
graph.rs(123, 99): required because it's used within this `async` fn body
decision.rs(64, 62): required because it's used within this `async` fn body
decision.rs(55, 62): required because it's used within this `async` fn body

**Comment by stefan-gorules** [comment]
Hi @andymk-dev,

Please see the following: https://github.com/gorules/zen/discussions/112. Let me know if this resolves your issues.

**Comment by andymk-dev** [comment]
Thanks for your prompt response!  Yes, this resolves my issue.
