### ISSUE TITLE
Add support for Boa in addition to (or instead of) QuickJS

### ISSUE THREAD

**Issue by yerke** [gorules/zen#128]
Hello.

It looks like Boa’s conformance with test262 is on part with QuickJS now. Would you be open to adding support for Boa in functions, perhaps behind a feature flag?

Thanks. 

https://boajs.dev/blog/2024/03/07/boa-release-18
https://github.com/boa-dev/boa
https://test262.fyi/

**Comment by stefan-gorules** [comment]
Hi @yerke,

Those are some amazing news, thanks for bringing this to our attention as we've wanted to use Boa in the past.

We will have a look at this. It might take some time as we have a lot of things going on in the background. What I had a quick look at:
- Size - Boa will increase the engine size by ~4MB which is mostly acceptable
- Performance - For simple expressions it looks great, but when we need to "pre-compile" modules the performance takes a dive.

Some questions on performance if you are familiar with boa (@yerke):
1. Are we able to pre-compile JavaScript modules such as day.js and big.js? (this is essentially serialisation of the context/module state)
2. Are we able to limit the time of Boa.JS context without spawning a new system thread? I'm happy with using tokio green threads if that's possible?

We’re also excited about potential prospect of bringing the full business rules engine into browsers through WASM.

**Comment by yerke** [comment]
Hi @stefan-gorules,

I am not very familiar with Boa myself, unfortunately. I am mostly interested in it from the point of making Gorules easier to build/consume.

I did read their docs and examples a bit to help answer your questions.

Re compilation of JS modules: Boa provides API to load, link, and evaluate modules: https://docs.rs/boa_engine/latest/boa_engine/module/struct.Module.html#method.load

Example of using modules: https://github.com/boa-dev/boa/blob/main/examples/src/bin/modules.rs

Re runtime limits: I have seen they mention it in their blog post: https://boajs.dev/blog/2024/03/07/boa-release-18#runtime-limits

**Comment by yerke** [comment]
Boa devs in the Discord channel [said](https://discord.com/channels/595323158140158003/595382036215365633/1217935285522796584) that `link` method actually does compiles modules to the bytecode.

**Comment by stefan-gorules** [comment]
I see. Based on this example https://github.com/boa-dev/boa/blob/main/examples/src/bin/modules.rs it seems that you still need Context in order to link (and therefore compile) a module. And from what I can tell based on the [docs](https://docs.rs/boa_engine/latest/boa_engine/context/struct.Context.html), there's no way to Clone a Context or create a base VM snapshot that can be serialized / deserialized for quick re-use.

Our ideal approach is mostly aligned with what [LLRT by Amazon](https://github.com/awslabs/llrt) is trying to achieve, just in context of rules engines and workflows.

**Comment by yerke** [comment]
@stefan-gorules If I understand correctly, you can just clone [Module](https://docs.rs/boa_engine/latest/boa_engine/module/struct.Module.html) struct and then it will be reused. Boa devs [told](https://discord.com/channels/595323158140158003/595382036215365633/1217961480268419072) me the same:
> as long as you keep using the same Module object, the module will reuse the same bytecode.
