### ISSUE TITLE
esbuild fails with - No loader is configured for ".node" files

### ISSUE THREAD

**Issue by mattrochon** [gorules/zen#131]
Trying to build my project with esbuild, index.js throws errors for all of the binary targets.

![image](https://github.com/gorules/zen/assets/1702787/45ff48f3-85bb-43f7-86df-3916e4e35b96)

**Comment by stefan-gorules** [comment]
Hi @mattrochon,

To resolve the above issue you would need to use .node loader. See: https://github.com/evanw/esbuild/issues/1051. Let me know if this helps.

**Comment by mattrochon** [comment]
I have tried that solution but it is not able to resolve the files on deployment to a lambda function.
The plugin proposed there tries to load all of the binaries, even ones that havent been installed and fails.

Bit out of my depth on this bundling stuff but very much would like to be able to use the node engine in my lambda function.

**Comment by stefan-gorules** [comment]
@mattrochon What specific set-up are you using (e.g. aws starter template, esbuild template, etc.)?

**Comment by mattrochon** [comment]
I'm not sure how to get this to build properly using esbuild. Do you have any insight here?

**Comment by mattrochon** [comment]
ok, add

--external:@gorules/zen-engine

and make sure your node modules has the binary targets you need

and itll work

**Comment by stefan-gorules** [comment]
Thanks for sharing! I'll close the issue now.

**Comment by raymondKelly** [comment]
> ok, add
> 
> --external:@gorules/zen-engine
> 
> and make sure your node modules has the binary targets you need
> 
> and itll work

@mattrochon I'm in a very similar position to yourself. Why would you mark zen-engine as an external module? Are you also copying that into the lambda? Would you mind sharing your esbuild config? 

Thanks for any help you can provide

**Comment by tokict** [comment]
So, copy it in the lambda and exclude specific platforms used. If you do local seploy from mac, then exclude darwin one, and if you do it via GH actions, exclude the x64 one like so:

<img width="509" alt="Screenshot 2024-10-25 at 11 42 39" src="https://github.com/user-attachments/assets/bf7972ec-26d7-493d-8ca8-12c4138cf6e5">
