### ISSUE TITLE
Invitation email links are set to `localhost:4200`

### ISSUE THREAD

**Issue by brez** [gorules/zen#150]
This is the docker container. When I send out invitations for users the email contains a link to `localhost` eg.

`http://localhost:4200/invitation/6e003bd~`

 I'm actually running it on port `9200` (not `4200`) - read thru the docs but I don't see any ref to setting the hostname and port for invitation emails. Is it an `env` variable?

**Comment by ivanmiletic** [comment]
Hi @brez please try with  APP_URL env

**Comment by brez** [comment]
That was it - thanks!
