### ISSUE TITLE
Where can I check the changes between versions?

### ISSUE THREAD

**Issue by eko234** [gorules/zen#151]
Hi, I'm trying to understand the changes between versions but I can't seem to find where this is documented, I'm going from 0.8.0 to the current one (0.20.0). Thanks.

**Comment by stefan-gorules** [comment]
Hi @eko234, this is on our radar. Currently we don't have changelogs, however there should be no breaking changes between the versions.

Are there any issues that you've faced?

**Comment by eko234** [comment]
Hi, not really, just wanted to know if there were any breaking changes, thanks!
