### ISSUE TITLE
explicitly force expression mode

### ISSUE THREAD

**Issue by eko234** [gorules/zen#156]
Hi, I want to know if theres a way to force expression mode without calling "cash sign" `$`, I'm using the nodejs bindings for gorules, so right now I'm using a dirty hack, that is: prefixing any expression with `($ != null) or ...` so I just wanted to know, thanks.

**Comment by stefan-gorules** [comment]
Hi @eko234, would you be able to provide an example of where you'd need this. Is the current behaviour causing a confusion in some cases, and if so in which ones?

**Comment by eko234** [comment]
Hello, yes I'm trying to use the engine as a backend to evaluate expressions, but I don't want them to be tied to an input always, so expressions like "1 == 1" can evaluate as truthy without depending on being bound to an input, so for this to work, my workaround is to do "($ == null) or (1 == 1)", where "1 ==1" is any expression I would like to evaluate. Hope the example is clear, the current behavior is fine when inputs are tied to expressions, but I think being able to start in expression mode without calling `$` would be neat.

**Comment by stefan-gorules** [comment]
Would you be able to use something like this instead? 
<img width="784" alt="image" src="https://github.com/gorules/zen/assets/127550877/0df59619-c534-45df-9747-30cc7139758f">

If you don't define a selector in Input, you can use free form expressions like above.

**Comment by eko234** [comment]
Mmmmm, I understand, yes yes, it makes sense, but, even if I don't define a selector can I reference the context in some rows?

**Comment by eko234** [comment]
I just tried it myself and it works just like that, I can set no selector and explicitly reference the context freely from any cell, thank you so much, I was expecting for this a long time :V
