### ISSUE TITLE
And/Or operator not working in array filter inside input cell

### ISSUE THREAD

**Issue by jonshofman** [gorules/zen#170]
Hey guys,

Can it be that and/or operators are not working when used in an array filter inside an input cell?

If tried the folllowing expression:

![image](https://github.com/gorules/zen/assets/75793085/8b679db6-5801-4725-9160-fbce28bd5bf0)

The left side in the input cell doesn't evaluate to true, while the right side in the output cell the same expression does evaluate to true (remove one of the conditions on the left to see).

Here's the simple json to test:

```{
  "items": [
    {
      "id": 1,
      "name": "test_1"
    },
    {
      "id": 2,
      "name": "test_2"
    },
  ],
}```



[graph.json](https://github.com/gorules/zen/files/15429285/graph.json)

**Comment by stefan-gorules** [comment]
Hi, above does not work as you are in unary mode as soon as you declare a selector for a column.

See below:
<img width="1400" alt="image" src="https://github.com/gorules/zen/assets/127550877/38c27dce-69e1-42c8-9d0e-57aafb0cfd40">

In the expression it's quite easy to see that everything is okay. See below table without selector:

<img width="1114" alt="image" src="https://github.com/gorules/zen/assets/127550877/f54e1f7d-282a-48eb-a25d-8b276ac1a851">

Which resolves the issue.

**Comment by jonshofman** [comment]
Hi Stefan.

Thanks for the quick reply!

Not exactly sure I understand how this is supposed to work.

Should I pass the expressions through a expressions node before hitting the decisionTable like so:

![image](https://github.com/gorules/zen/assets/75793085/fdd305ac-1a58-45da-98ca-66a7326c42aa)

And the evaluate the output of the expression in the individual table cells?

**Comment by jonshofman** [comment]
Nevermind I think I get it :)

**Comment by ivanmiletic** [comment]
Hi, can we close this? It works in expression mode, not in unary mode

**Comment by jonshofman** [comment]
Yes sure, thanks.
