### ISSUE TITLE
No loader is configured for ".node" files: node_modules/@gorules/zen-engine-darwin-arm64/zen-engine.darwin-arm64.node

### ISSUE THREAD

**Issue by cgrisar** [gorules/zen#172]
Anyone experienced this error?

Developing with VSCode
Using vite.js on macOS

**Comment by ivanmiletic** [comment]
Hi @cgrisar , zen-engine is built to be used on NodeJS backend.
We do not have a support for Frontend, there are some ideas to support WASM but are not planned for this year.
