### ISSUE TITLE
Running date operations on several inputs

### ISSUE THREAD

**Issue by psamaan** [gorules/zen#189]
This seems like something I should be able to do, but I can't figure out how to get it to work.
I am trying to do date comparisons between different properties in the input and set an output as a result. I've tried referencing properties by name, and wrapping in a date() function, but can't get any output. I'm also not able to confirm from the trace whether my inputs were parsed at all.

I'm using gorules.io editor in a project to test all this.

![image](https://github.com/gorules/zen/assets/4834419/962feaec-6f05-4dc3-88df-d3f79d2adacf)

**Comment by stefan-gorules** [comment]
Hi @psamaan, could you try using:

```
date(property1.date)
```

and in some cases
```
> date(property2.date)
```

**Comment by psamaan** [comment]
Yup, that worked. I must have only wrapped the rows in date() and not the column selectors. Thanks!
