### ISSUE TITLE
extract function invalid

### ISSUE THREAD

**Issue by chengguotao** [gorules/zen#204]
extract('2022-02-01','(d{4})-(d{2})-(d{2})')
extract('foo.bar', '(w+).(w+)')
The extract function do not seem to work, returning "sptrs\":[]

**Comment by stefan-gorules** [comment]
Hi @chengguotao, you need to use backslashes `\`. Here's the fixed version:
<img width="923" alt="image" src="https://github.com/gorules/zen/assets/127550877/734698a7-6c1e-46d3-acb2-5af718454ac6">

**Comment by chengguotao** [comment]
aaa.bbb.ccc.ddd
How to split by '.', get all letters, (\w+).(\w+) This way can only get the first '.' match

**Comment by stefan-gorules** [comment]
Hi @chengguotao, for regex please have a look at https://regex101.com/. The crate that we use in particular is: https://docs.rs/regex-lite/latest/regex_lite/.
