### ISSUE TITLE
is Input modification functionality available?

### ISSUE THREAD

**Issue by shokri-navid** [gorules/zen#209]
Based on a condition, I am trying to set a discount percentage on my input. but I did not find any documentation about that.
for example, I have this input: 

```json
{
  "country" : "US",
  "discount": null
}
```
and I expected that if the `country` is `US` the response should be: 

``` json
{
  "input":{
    "country" : "US",
    "discount": null
  }
}

**Comment by stefan-gorules** [comment]
Hi, please have a look at our example: https://gorules.io/docs/user-manual/getting-started/tutorials/retail-shipping-fees.

It's somewhat outdated but should contain relevant information for your use case.
