### ISSUE TITLE
Calling zen.evaluate inside a function fails

### ISSUE THREAD

**Issue by bjorntheart** [gorules/zen#238]
I'm on a free trial of cloud on gorules.io

I have a function that calls `zen.evaluate()` on another decision that is published and get the following error
![Screenshot 2024-09-05 at 08 59 38](https://github.com/user-attachments/assets/952fa96d-662a-4069-8c7b-b947c8a06762)

**Comment by bjorntheart** [comment]
Please feel free to close

**Comment by bjorntheart** [comment]
Also, running `await zend.evaluate()` in 
```js
.map(async function(o) {
  // params left out for brevity
  await zen.evaluate(...)
})
```
doesn't work. 

What works is running it inside a regular for loop like so:
```js
for (const [k, bike] of Object.entries(bikes)) {
  let result = await zen.evaluate('ererer/insurables/bike.json', bike, { trace: true });
  console.log({ result });    
}
```

**Comment by ivanmiletic** [comment]
Hi Bjorn, we will take a look at it why it isn't working in map. Can you try:

await Promise.all(somelist.map(async () => {
  return await zen.evaluate();
}));

**Comment by bjorntheart** [comment]
Works like a charm, and right after you commented I remembered I had some code lying around doing just that.

```js
  let evaluated = await Promise.all(
    bikes.map(async function (insurable) {
      let r = await decision.evaluate(insurable, { trace: false });
      return { ...r.result, insurable };
    }),
  );
```

**Comment by stefan-gorules** [comment]
Closing as the thread has been resolved.
