### ISSUE TITLE
Loop behaviour

### ISSUE THREAD

**Issue by Gabrieltay** [gorules/zen#273]
Hi guys, thanks for releasing the `Passthrough` and `Loop` features.  They are awesome. 

Based on the documentation, the `Loop` should return an array of outputs based on the array of inputs

I have a simple JDM here 
[sample.json](https://github.com/user-attachments/files/17811819/sample.json)

using the following inputs
```json
{
  "items": [
    {
      hello: 'foo',
    },
    {
      hello: 'koo',
    },
  ],
}
```
Expected response:
```json
{
  res: [
    {
      world: 'bar',
    },
    {
      world: 'error',
    },
  ],
}
```

Actual response:
```json
{
  res: [
    {
      world: 'bar',
    },
    {
      world: 'bar',
    },
  ],
}
```

Is this behaviour expected?

Btw, I am using the latest Standalone Editor

**Comment by stefan-gorules** [comment]
Hi @Gabrieltay 

Thank you for the bug report. This has been confirmed and the fix will be released.
