### ISSUE TITLE
JDM specification and lifecycle management

### ISSUE THREAD

**Issue by sysid** [gorules/zen#53]
Thanks for this OSS contribution!
You are mentioning "[GoRules JSON Decision Model (JDM)](https://gorules.io/docs/rules-engine/json-decision-model) standard" as foundation of the rule engine on your documentation.

Is there some kind of formal specification of this "standard"?
How do you plan to manage lifecycle and evolvement of it?

**Comment by sysid** [comment]
thanks @stefan-gorules for your quick response! The link is helpful. but it does not seem to cover the required JDM json format.

Example:
When deleting the json-key `position` from your `./test-data/function.json` example, the evaluation fails with a loader error. So the key `position` seems to be mandatory in the JDM json files. 

I think for a json based DSL like JDM needs a specification which lists mandatory/optional fields, document structure, allowed values, etc....

Otherwise it is a bit of guesswork and try-and-error, based on the provided examples, to figure out what can be fed into the BRE. 

Using your superb editor https://editor.gorules.io/ is an option, of course. But it brings a very heavy dependency which is not appropriate for some use-cases.

**Comment by stefan-gorules** [comment]
Hi @sysid before closing you mentioned that removing the position causes the format to break, if this is the case I'm happy to open the issue and investigate it further as this should not happen.

**Comment by sysid** [comment]
Thanks @stefan-gorules, your attentiveness is much appreciated! 

My original remark was based on an error on my side. It is working.

Really looking forward to see the jdm-editor!
