### ISSUE TITLE
Closure with startsWith does not work as expected.

### ISSUE THREAD

**Issue by sysid** [gorules/zen#54]
I am trying to wrap my head around the closures. 
Given the expression: `some(["a", "b"], startsWith("xxx", #))`.
I would expect to get false back, but this does not work. 

What am I doing wrong? Since the expression just fails with no user feedback I wonder if I can get some debugging information?
Thank You!

**Comment by stefan-gorules** [comment]
Hi @sysid, thank you for the report. Confirmed it to be a bug (the above expression errors out). After merging the #55 and releasing through channels it should work as expected
