### ISSUE TITLE
Question: Is there a way to refference a part of the context in each input?

### ISSUE THREAD

**Issue by eko234** [gorules/zen#58]
Hi, I'm trying to use zen engine but I want to dinamically inject some variables, it's something quite similar to what the concept of expressionNodes are, but I can't find a way to do so. AFAIK, expression nodes are static and are the only way I know to be able to refference a value both in input and output fields.

**Comment by stefan-gorules** [comment]
Hi @eko234,
Would you be able to describe your use-case in more detail?

If you are looking to pass variables dynamically (e.g. based on service environment of your service), best way would be to pass some config map within the context (request), such as:
```ts
const context = {
  "config": {
    "someVariable": process.env.SOME_VARIABLE,
    ...rest,
  },
  ...restContext,
}
```

**Comment by eko234** [comment]
Hi @stefan-gorules!,
![image](https://github.com/gorules/zen/assets/38670883/125a36a4-8e26-4a8e-9657-e196d1cd1461)
I want to do something like this

**Comment by stefan-gorules** [comment]
Hi, to achieve this, you can write the expression under user.age as following:
`$ > minimumAge`, whereby declaring "$" references current column and enables access to other environment variables.

Let me know if that works.

**Comment by ivanmiletic** [comment]
Hi @eko234 , in the new version that is coming in a few weeks, selectors in the columns will be optional and with them the table cell will have full access to an expression, that is where you will be able to write user.age > minimumAge inside the cell.

**Comment by eko234** [comment]
> Hi, to achieve this, you can write the expression under user.age as following: `$ > minimumAge`, whereby declaring "$" references current column and enables access to other environment variables.
> 
> Let me know if that works.

Hi, thanks but I'm talking about minimumAge being a constant that I can somehow inject, is not something I would replace by myself with the actual value.

**Comment by eko234** [comment]
> Hi @eko234 , in the new version that is coming in a few weeks, selectors in the columns will be optional and with them the table cell will have full access to an expression, that is where you will be able to write user.age > minimumAge inside the cell.

Oh nice, this seems like an easier way to get what I need in a cleaner way, thanks.

**Comment by stefan-gorules** [comment]
After the overhaul of zen-expressions in #107 this is now supported. Thank you for reporting the issue.

<img width="1515" alt="image" src="https://github.com/gorules/zen/assets/127550877/a9275e66-778f-4dfa-871b-7f3ec2d4b9b7">
<img width="1496" alt="image" src="https://github.com/gorules/zen/assets/127550877/32d2be52-9bc8-4135-8f63-f03f94b28f54">
<img width="1501" alt="image" src="https://github.com/gorules/zen/assets/127550877/937f4202-e6e5-49e4-861e-aaa805fc3139">
