### ISSUE TITLE
Question: how can I define a string output that contains both quotes and single quotes as result 

### ISSUE THREAD

**Issue by eko234** [gorules/zen#59]
I can't seem to find how to do this, and also is there any documentation about escaping characters in general? like newlines, quotes, etc?

**Comment by ivanmiletic** [comment]
At the moment there isn't, can you provide us with some example?

**Comment by eko234** [comment]
Let's say I want to return "your secret word is \"hello\"", on the other hand I was wondering if there is a way to concatenate numbers to strings. I think I can find a way to do so with functions, but just wanted to know if there is a built-in way to do so, or if there are plans for something like this

**Comment by ivanmiletic** [comment]
Thanks Eko, it is not yet supported, we will see to enhance the engine to support concatenation in this way, you can concatenate two strings but not yet string and number

**Comment by stefan-gorules** [comment]
Hi @eko234, template strings have just been merged.

see #225
