### ISSUE TITLE
Question: how can I concatenate a string with a number in the output?

### ISSUE THREAD

**Issue by Wilfred-Shu** [gorules/zen#69]
I can't seem to find how to do this and the documentation did not mention how to do conversion between different data types using the zen expression. (e.g. number to string)

**Comment by stefan-gorules** [comment]
Sounds reasonable, we'll scope out operators for conversion such as: `string`, `number`, `bool`, and potentially `json` for string -> object/array.

**Comment by stefan-gorules** [comment]
We've added some conversion types from in: https://github.com/gorules/zen/pull/94

`bool` we've decided not to as it's simple to write e.g. `x == "true"`, and `json` will be added in future as well.
